[build]
  command = "npm run build"
  publish = ".next"
  
[build.environment]
  NODE_VERSION = "18"
  NEXT_USE_NETLIFY_EDGE = "true"
  
[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  # Increase timeout for document processing functions
  "src/app/api/upload-document/route" = { timeout = 25 }
  "src/app/api/analyze-document/route" = { timeout = 25 }

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"